# Generated by Django 4.2.7 on 2023-12-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimagesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmarkdownmodel',
            name='project_markdown',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
